package com.rockstock.backend.entity.stock;

public enum StockChangeType {
    PURCHASE_RECEIVED,
    CUSTOMER_RETURN,
    STOCK_ADJUSTMENT_POSITIVE,
    SALES_DISPATCHED,
    RETURN_TO_SUPPLIER,
    STOCK_ADJUSTMENT_NEGATIVE,
    DAMAGED_OR_EXPIRED,
    TRANSFER
}